// users
export const FETCH_USERS = 'FETCH_USERS'
export const CREATE_USER = 'CREATE_USER'
export const DELETE_USER = 'DELETE_USER'
export const USERS_API_SUCCESS = 'USERS_API_SUCCESS'
export const USERS_API_FAILURE = 'USERS_API_FAILURE'

// session
export const CREATE_SESSION = 'CREATE_SESSION'
export const DELETE_SESSION = 'DELETE_SESSION'
export const SESSION_API_SUCCESS = 'SESSION_API_SUCCESS'
export const SESSION_API_FAILURE = 'SESSION_API_FAILURE'